### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Quadsam** [CarterWilde/bottega-ticket-notifications#2]
When I run the program I get the error:
`0 info it worked if it ends with ok`
`1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',`
`1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',`
`1 verbose cli   'start',`
`1 verbose cli   '-P=\'start\'' ]`
`2 info using npm@6.9.0`
`3 info using node@v10.16.0`
`4 verbose run-script [ 'prestart', 'start', 'poststart' ]`
`5 info lifecycle bottega-ticket-notifications@1.0.0~prestart: bottega-ticket-notifications@1.0.0`
`6 info lifecycle bottega-ticket-notifications@1.0.0~start: bottega-ticket-notifications@1.0.0`
`7 verbose lifecycle bottega-ticket-notifications@1.0.0~start: unsafe-perm in lifecycle true`
`8 verbose lifecycle bottega-ticket-notifications@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Sam\Downloads\bottega-ticket-notifications-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\mingw32\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\SFML-2.5.1\include\;C:\Program Files\dotnet\;C:\Users\Sam\AppData\Local\Programs\Python\Python37-32;C:\Users\Sam\AppData\Local\Programs\Python\Python37-32\Scripts;C:\WSJT\wsjtx\bin;C:\PROGRA~2\FANUC\Shared\UTILIT~1;C:\PROGRA~2\FANUC\WinOLPC\bin;C:\Program Files\CMake\bin;C:\Program Files\nodejs\;C:\Users\Sam\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\Sam\AppData\Local\Programs\Python\Python37-32\;C:\Users\Sam\AppData\Local\Microsoft\WindowsApps;C:\Users\Sam\AppData\Local\GitHubDesktop\bin;C:\Users\Sam\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Sam\AppData\Roaming\npm`
`9 verbose lifecycle bottega-ticket-notifications@1.0.0~start: CWD: C:\Users\Sam\Downloads\bottega-ticket-notifications-master`
`10 silly lifecycle bottega-ticket-notifications@1.0.0~start: Args: [ '/d /s /c', 'node main.js "\'start\'"' ]`
`11 silly lifecycle bottega-ticket-notifications@1.0.0~start: Returned: code: 1  signal: null`
`12 info lifecycle bottega-ticket-notifications@1.0.0~start: Failed to exec start script`
`13 verbose stack Error: bottega-ticket-notifications@1.0.0 start: `node main.js "'start'"``
`13 verbose stack Exit status 1`
`13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)`
`13 verbose stack     at EventEmitter.emit (events.js:198:13)`
`13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)`
`13 verbose stack     at ChildProcess.emit (events.js:198:13)`
`13 verbose stack     at maybeClose (internal/child_process.js:982:16)`
`13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)`
`14 verbose pkgid bottega-ticket-notifications@1.0.0`
`15 verbose cwd C:\Users\Sam\Downloads\bottega-ticket-notifications-master`
`16 verbose Windows_NT 10.0.17763`
`17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "-P='start'"`
`18 verbose node v10.16.0`
`19 verbose npm  v6.9.0`
`20 error code ELIFECYCLE`
`21 error errno 1`
`22 error bottega-ticket-notifications@1.0.0 start: `node main.js "'start'"``
`22 error Exit status 1`
`23 error Failed at the bottega-ticket-notifications@1.0.0 start script.`
`23 error This is probably not a problem with npm. There is likely additional logging output above.`
`24 verbose exit [ 1, true ]`

**Comment by Quadsam** [comment]
[2019-06-14T15_51_23_868Z-debug.log](https://github.com/CarterWilde/bottega-ticket-notifications/files/3291350/2019-06-14T15_51_23_868Z-debug.log)

**Comment by CarterWilde** [comment]
try running it with this
`node main.js -P='start'`

**Comment by Quadsam** [comment]
error: unknown option `-''

**Comment by CarterWilde** [comment]
Sorry my bad
`node main.js -P start`

**Comment by Quadsam** [comment]
give the error:

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn start ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by CarterWilde** [comment]
What happens if you remove lines 70 - 73 and line 62?

**Comment by Quadsam** [comment]
it only goes to 72

**Comment by Quadsam** [comment]
but this is the last lines of code is this what i should remove ?

function playSound() {
    const { spawn } = require('child_process');
    const audio = spawn(AudioPlayerCmd, [SoundPath]);
}

**Comment by Quadsam** [comment]
i removed line 62 and it works now

**Comment by CarterWilde** [comment]
Okay, since you're on windows it notify should still play a sound and show you a card.
